export type SourceRecord = {
  id: string;
  source: string;
  dataset: string;
  asOf: string;
  freshness: string;
  confidence: "High" | "Medium";
  method: string;
  status: "Verified" | "Corroborated" | "Reference";
  url: string;
  note: string;
};

export const PRICE_HISTORY = [
  { month: "Sep ’25", observed: 282, base: null, bull: null, bear: null },
  { month: "Oct", observed: 272, base: null, bull: null, bear: null },
  { month: "Nov", observed: 271, base: null, bull: null, bear: null },
  { month: "Dec", observed: 264, base: null, bull: null, bear: null },
  { month: "Jan ’26", observed: 278, base: null, bull: null, bear: null },
  { month: "Feb", observed: 298, base: null, bull: null, bear: null },
  { month: "Mar", observed: 307.5, base: null, bull: null, bear: null },
  { month: "Apr", observed: 319, base: null, bull: null, bear: null },
  { month: "May", observed: 310, base: null, bull: null, bear: null },
  { month: "Jun", observed: 280, base: null, bull: null, bear: null },
  { month: "Jul", observed: 280, base: null, bull: null, bear: null },
  { month: "Aug", observed: 286, base: null, bull: null, bear: null },
  { month: "Sep", observed: 282.5, base: 282.5, bull: 282.5, bear: 282.5 },
] as const;

export const LCB_PRICES = [
  { origin: "South Africa", grade: "36/38", product: "Lump", mode: "Truck", basis: "FOT Rustenburg", currency: "ZAR", price: 1650 },
  { origin: "South Africa", grade: "40/42", product: "Concentrate", mode: "Truck", basis: "FOT Rustenburg", currency: "ZAR", price: 2550 },
  { origin: "South Africa", grade: "42/44", product: "Concentrate", mode: "Truck", basis: "FOT Rustenburg", currency: "ZAR", price: 3300 },
  { origin: "South Africa", grade: "44/46", product: "Concentrate", mode: "Truck", basis: "FOT Rustenburg", currency: "ZAR", price: 3750 },
  { origin: "South Africa", grade: "40/42", product: "Concentrate", mode: "Truck", basis: "DAP City Deep", currency: "ZAR", price: 2950 },
  { origin: "South Africa", grade: "40/42", product: "Concentrate", mode: "Truck", basis: "DAP Richards Bay", currency: "ZAR", price: 3350 },
  { origin: "South Africa", grade: "36/38", product: "Lump", mode: "Bulk", basis: "CIF China", currency: "USD", price: 255 },
  { origin: "South Africa", grade: "38/40", product: "ROM", mode: "Bulk", basis: "CIF China", currency: "USD", price: 245 },
  { origin: "South Africa", grade: "38/40", product: "Lump", mode: "Bulk", basis: "CIF China", currency: "USD", price: 277 },
  { origin: "South Africa", grade: "40/42", product: "ROM", mode: "Bulk", basis: "CIF China", currency: "USD", price: 265 },
  { origin: "South Africa", grade: "40/42", product: "Concentrate", mode: "Bulk", basis: "CIF China", currency: "USD", price: 288 },
  { origin: "South Africa", grade: "40/42", product: "Concentrate", mode: "Container", basis: "CIF China", currency: "USD", price: 265 },
  { origin: "South Africa", grade: "42/44", product: "Concentrate", mode: "Bulk", basis: "CIF China", currency: "USD", price: 300 },
  { origin: "South Africa", grade: "42/44", product: "Concentrate", mode: "Container", basis: "CIF China", currency: "USD", price: 290 },
  { origin: "Zimbabwe", grade: "48/50", product: "Concentrate", mode: "Bulk", basis: "CIF China", currency: "USD", price: 360 },
  { origin: "Zimbabwe", grade: "48/50", product: "Concentrate", mode: "Container", basis: "CIF China", currency: "USD", price: 345 },
] as const;

export const FREIGHT_MARKET = [
  { size: "SMX 50k / 10%", route: "RBCT → WCI", commodity: "Coal", terms: "10kt SHINC bends", low: 25, high: 26 },
  { size: "SMX 50k / 10%", route: "Mtwara → WCI", commodity: "Coal", terms: "10kt SHINC bends", low: 22, high: 23 },
  { size: "SMX 50k / 10%", route: "Maputo → WCI", commodity: "Coal", terms: "10kt SHINC bends", low: 25, high: 26 },
  { size: "SMX 50k / 10%", route: "Maputo → Qingdao", commodity: "Iron ore", terms: "10kt SHINC bends", low: 33, high: 34 },
  { size: "SMX 50k / 10%", route: "San Pedro → Qingdao", commodity: "Iron ore", terms: "10kt SHINC bends", low: 41, high: 42 },
  { size: "SMX 50k / 10%", route: "Durban → Tianjin", commodity: "Chrome", terms: "10kt SHINC bends", low: 35, high: 36 },
  { size: "PMX 75k / 10%", route: "RBCT → WCI", commodity: "Coal", terms: "10kt SHINC bends", low: 25, high: 26 },
  { size: "PMX 75k / 10%", route: "Saldanha → Qingdao", commodity: "Iron ore", terms: "10kt SHINC bends", low: 35, high: 36 },
  { size: "PMX 75k / 10%", route: "RBCT → ARA", commodity: "Coal", terms: "10kt SHINC bends", low: 30, high: 31 },
  { size: "Cape 150k / 10%", route: "RBCT → ARA", commodity: "Coal", terms: "10kt SHINC bends", low: 20, high: 21 },
] as const;

export const SOURCES: SourceRecord[] = [
  {
    id: "smm-price",
    source: "Shanghai Metals Market",
    dataset: "SA chrome ore price assessment",
    asOf: "21 Sep 2026",
    freshness: "Same day",
    confidence: "High",
    method: "Published assessment",
    status: "Verified",
    url: "https://www-old.metal.com/price/Minor-Metals/Chromium",
    note: "40–42% concentrate CIF China at $280–285/dmt; $282.50 midpoint, unchanged on the day.",
  },
  {
    id: "lcb-sheet",
    source: "London Commodity Brokers",
    dataset: "SA & Zimbabwe chrome quotes",
    asOf: "15 Sep 2026 batch",
    freshness: "6 days",
    confidence: "Medium",
    method: "Broker market sheet",
    status: "Corroborated",
    url: "https://www.londoncommoditybrokers.com/",
    note: "User-supplied snapshot. Quote basis, moisture, sizing and payment terms require deal-level confirmation.",
  },
  {
    id: "nexus-freight",
    source: "Nexus Shipping / LCB",
    dataset: "Dry-bulk freight indications",
    asOf: "15 Sep 2026",
    freshness: "6 days",
    confidence: "Medium",
    method: "Broker indication",
    status: "Corroborated",
    url: "https://www.londoncommoditybrokers.com/",
    note: "Durban–Tianjin chrome indication at $35–36/mt for 10kt SHINC bends.",
  },
  {
    id: "smm-stock",
    source: "Shanghai Metals Market",
    dataset: "China port chrome inventory",
    asOf: "11 Sep 2026",
    freshness: "10 days",
    confidence: "High",
    method: "Published inventory survey",
    status: "Verified",
    url: "https://news.metal.com/newscontent/104113766-smm-chromium-flash-chinas-chrome-ore-port-inventory-climbs-to-532-mt-as-of-sep-11-tianjin-up-qinzhou-down",
    note: "5.318 Mt total, up 98.6 kt (+1.89%) week on week; Tianjin at 4.6854 Mt.",
  },
  {
    id: "smm-exports",
    source: "Shanghai Metals Market",
    dataset: "South African chrome exports",
    asOf: "Jul 2026",
    freshness: "Latest SARS month",
    confidence: "High",
    method: "Trade-data analysis",
    status: "Verified",
    url: "https://news.metal.com/newscontent/104096220-smm-chromium-flash-south-africas-july-chrome-ore-exports-hit-2026-high-of-265-mt-as-buyer-base-broadens",
    note: "July exports near 2.65 Mt, +10.3% month on month and the highest reported level of 2026.",
  },
  {
    id: "sarb-fx",
    source: "South African Reserve Bank",
    dataset: "USD/ZAR weighted-average reference rate",
    asOf: "18 Sep 2026",
    freshness: "Latest business day",
    confidence: "High",
    method: "Official daily reference rate",
    status: "Verified",
    url: "https://www.resbank.co.za/en/home/what-we-do/statistics/key-statistics/selected-historical-rates",
    note: "Latest published SARB reference used by the dashboard: 1 USD = R16.2630.",
  },
  {
    id: "fastmarkets",
    source: "Fastmarkets",
    dataset: "MB-CHO-0003 methodology",
    asOf: "Current specification",
    freshness: "Reference",
    confidence: "High",
    method: "Price methodology",
    status: "Verified",
    url: "https://www.fastmarkets.com/uploads/2025/02/fm-mb-non-ferrous-methodology-specifications.pdf",
    note: "Weekly CIF Tianjin assessment for 40–42% bulk concentrate, normalized to minimum 5,000 tonnes.",
  },
  {
    id: "sars",
    source: "SARS",
    dataset: "Official trade statistics · HS 261000",
    asOf: "Monthly release",
    freshness: "Reference",
    confidence: "High",
    method: "Government customs data",
    status: "Reference",
    url: "https://www.sars.gov.za/customs-and-excise/trade-statistics/",
    note: "Primary verification route for South African export volumes and destinations.",
  },
  {
    id: "itac",
    source: "ITAC / South African Government",
    dataset: "Chrome ore export-control policy",
    asOf: "Policy watch",
    freshness: "Event-driven",
    confidence: "High",
    method: "Official notice",
    status: "Reference",
    url: "https://www.gov.za/documents/notices/international-trade-administration-act-placing-chrome-ore-under-export-control-0",
    note: "Consultation notice is tracked as a structural risk; current legal status must be verified before commercial action.",
  },
  {
    id: "dmpr-fuel",
    source: "DMPR",
    dataset: "Official South African fuel-price adjustments",
    asOf: "Monthly release",
    freshness: "Monthly",
    confidence: "High",
    method: "Government price schedule",
    status: "Reference",
    url: "https://www.dmpr.gov.za/Services/Petroleum-Resources/Fuel-Prices",
    note: "Primary fuel-surcharge input. The September 2026 diesel movement must be applied to the carrier's agreed base month, not treated as a complete freight rate.",
  },
  {
    id: "sanral-tolls",
    source: "SANRAL / South African Government",
    dataset: "2026 national toll tariffs",
    asOf: "1 Mar 2026",
    freshness: "Annual / event-driven",
    confidence: "High",
    method: "Official tariff notice",
    status: "Verified",
    url: "https://www.gov.za/documents/notices/south-african-national-roads-agency-limited-and-national-roads-act-toll-tariffs",
    note: "Class 4 tolls are used as auditable lane-cost inputs. Tariffs include VAT and must be mapped to the actual route and vehicle class.",
  },
  {
    id: "rfa-vci",
    source: "Road Freight Association",
    dataset: "Vehicle Cost Index / cost schedules",
    asOf: "Current edition",
    freshness: "Subscription reference",
    confidence: "High",
    method: "Industry costing model",
    status: "Reference",
    url: "https://rfa.co.za/SA/vehicle-cost-schedule/",
    note: "Useful for cost-per-kilometre calibration across vehicle types. It is a hypothetical costing model, not evidence of a carrier's quoted market rate.",
  },
] as const;

export const TRANSPORT_LANES = [
  { id: "city-deep", label: "Rustenburg → City Deep", distanceKm: 145, tollsZar: 300, observedBasisZarPerT: 400, evidence: "LCB FOT-to-DAP spread" },
  { id: "richards-bay", label: "Rustenburg → Richards Bay", distanceKm: 720, tollsZar: 1600, observedBasisZarPerT: 800, evidence: "LCB FOT-to-DAP spread" },
  { id: "durban", label: "Rustenburg → Durban", distanceKm: 730, tollsZar: 1850, observedBasisZarPerT: null, evidence: "No verified carrier quote" },
  { id: "maputo", label: "Rustenburg → Maputo", distanceKm: 610, tollsZar: 1450, observedBasisZarPerT: null, evidence: "Border / permit costs excluded" },
] as const;

export const DATA_CONNECTORS = [
  { source: "SARS trade statistics", layer: "Exports", cadence: "Monthly", mode: "Approved file / publication", cost: "Free", readiness: "Foundation" },
  { source: "DMPR fuel prices", layer: "Road cost", cadence: "Monthly", mode: "Official publication", cost: "Free", readiness: "Foundation" },
  { source: "SANRAL toll tariffs", layer: "Road cost", cadence: "Annual", mode: "Official notice / PDF", cost: "Free", readiness: "Foundation" },
  { source: "Carrier RFQ ledger", layer: "Executed transport", cadence: "Quote event", mode: "Forms / SharePoint", cost: "Internal", readiness: "Highest priority" },
  { source: "Azure Maps Route Matrix", layer: "Truck distance", cadence: "On route change", mode: "REST API", cost: "Usage based", readiness: "Adapter ready" },
  { source: "TollGuru", layer: "Route tolls", cadence: "On route change", mode: "REST API", cost: "Paid", readiness: "Optional adapter" },
  { source: "Fastmarkets", layer: "Chrome benchmark", cadence: "Published schedule", mode: "Licensed API", cost: "Paid", readiness: "Optional adapter" },
  { source: "S&P Global Commodity Insights", layer: "Metals + dry freight", cadence: "Intraday / daily", mode: "Licensed API / feed", cost: "Paid", readiness: "Optional adapter" },
  { source: "SMM", layer: "Prices + port stocks", cadence: "Daily / weekly", mode: "Subscription / approved delivery", cost: "Paid", readiness: "Optional adapter" },
] as const;

export const MARKET_EVENTS = [
  { date: "21 Sep", event: "SMM CIF 40–42 midpoint", value: "$282.50/dmt", impact: "Stable" },
  { date: "21 Sep", event: "Tianjin 40–42 in-whs", value: "$7.02/dmtu", impact: "Firming" },
  { date: "18 Sep", event: "SARB USD/ZAR reference", value: "16.2630", impact: "Reference" },
  { date: "15 Sep", event: "Durban → Tianjin freight", value: "$35–36/mt", impact: "Neutral" },
  { date: "14 Sep", event: "Global chrome departures", value: "479.7 kt · −30.66% WoW", impact: "Supportive" },
  { date: "11 Sep", event: "China port stocks", value: "5.318 Mt · +1.89%", impact: "Bearish" },
] as const;
